
[project]
name = "leakpro"
version = "0.1.0"
description = "A package for privacy risk analysis"
authors = [{name = "LeakPro team", email = "johan.ostman@ai.se"}]
readme = "README.md"
license = {file="LICENSE"}
requires-python = '>=3.8,<3.13'

dependencies = [
  "numpy",
  "pandas",
  "scipy",
  "matplotlib",
  "seaborn",
  "dotmap",
  "jinja2",
  "tqdm",
  "joblib",
  "pyyaml",
]

[project.optional-dependencies]
<<<<<<< HEAD
mia = [
  "torch", 
  "torchvision", 
<<<<<<< HEAD
  "torchmetrics",
<<<<<<< HEAD
  "dotmap",
  "loguru",
  "jinja2",
  "tqdm",
  "pyyaml",
  "numba",
  "pydantic",
  "joblib",
  "pytest",
  "pytest-mock",
  "gdown",
  "optuna",
  "pytorch-ignite",
=======
>>>>>>> 44b435d (added dependencies for each subpackage)
=======
>>>>>>> bad23c7 (started subpackages)
]
synthetic = [
  "numba", 
  "pydantic"
]
federated = [
  "torch", 
  "torchvision", 
  "torchmetrics",
]

=======
mia = ["torch", "torchvision"]
synthetic = ["numba", "pydantic"]
federated = ["torch", "torchvision", "torchmetrics",]
<<<<<<< HEAD
<<<<<<< HEAD
dev = ["torch", "torchvision", "torchmetrics", "numba", "pydantic", "pytest", "pytest-cov", "ruff"]
>>>>>>> 6175f08 (updated factory + toml)
=======
dev = ["pytest", "pytest-cov", "pytest-mock", "coverage-badge", "ruff"] + mia + synthetic + federated
>>>>>>> 3a3fd6d (use toml for installation in CICD)
=======
dev = [
  "pytest",
  "pytest-cov",
  "pytest-mock",
  "coverage-badge",
  "ruff",
  "torch",  # from mia & federated
  "torchvision",  # from mia & federated
  "torchmetrics",  # from federated
  "numba",  # from synthetic
  "pydantic",  # from synthetic
  "scikit-learn", # from synthetic
]
>>>>>>> 401cb4b (toml apparently not supporting list concatenation)

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["leakpro*"]

[tool.ruff]
line-length = 130
target-version = "py39"

select = [
  "ANN", "ARG", "B", "C4", "C90", "D", "DTZ", "E", "ERA", "F", "I", "N", "PD", "PGH", "PLC",
  "PLE", "PLR", "PLW", "PT", "Q", "RET", "S", "SIM", "T20", "TID", "W",
]

exclude = [
  ".venv",
  "./tests",
  "./leakpro/tests",
  "./examples",
]

lint.ignore = [
  "D401", # non-imperative-mood
  "PD901", # Avoid using df variable name as pd.Dataframe
  "PD011", # pandas-use-of-dot-values
  "PLR0913", # too-many-arguments in function
  "S101", # Using assert
  "PLR2004", # magic-value-comparison
  "D107", # Missing docstring in `__init__`
  "PLW2901", # redefined-loop-name
  "D202", # No blank lines allowed after function docstring
  "F811" # redefinition of function
]
