name: Running tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  code-checks-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff Linting
        run: |
          pip install ruff
          ruff check leakpro --exclude examples,leakpro/tests

      - name: Install pytest and pytest-cov
        run: |
          pip install pytest pytest-cov

      - name: Run tests with pytest
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=leakpro leakpro/tests/ | tee pytest-coverage.txt
          cat ./pytest-coverage.txt

      - name: Upload test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage.txt
          path: pytest-coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: pytest-coverage.txt
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true